// Ezoterik semboller ansiklopedisi (tarayıcı + sunucu): 32 sembol, kategoriler, köken, anlam ve günümüzdeki kullanım.
// Dinî ve kültürel kökenli semboller saygılı ve tarafsız bir dille anlatılır.
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.SembolVeri = factory();
})(typeof self !== "undefined" ? self : this, () => {
  const kategoriler = {
    koruma: "Koruma",
    geometri: "Kutsal geometri",
    dongu: "Döngü ve sonsuzluk",
    bilgelik: "Bilgelik ve uyanış",
    doga: "Doğa ve dönüşüm",
    gok: "Gök ve ışık",
  };

  const S = (id, ad, kategori, koken, anahtar, anlam, kullanim) => ({ id, ad, kategori, koken, anahtar, anlam, kullanim });

  const semboller = [
    S("nazar", "Nazar Boncuğu", "koruma", "Anadolu, Akdeniz ve Orta Doğu; binlerce yıllık cam boncuk geleneği", ["kem gözden korunma", "şans", "bereket"],
      "Mavi cam göz, kıskanç ya da kötü bakışın enerjisini kendi üzerine çekip geri yansıttığına inanılan en tanıdık koruma sembolüdür. Kırıldığında 'görevini yaptığı' söylenir.",
      "Kapı girişine, bebek beşiğine, arabaya ya da takı olarak üzerine; yeni başlangıçlarda hediye edilir."),
    S("hamsa", "Hamsa", "koruma", "Orta Doğu ve Kuzey Afrika; farklı inanç gelenekleri tarafından ortak kullanılır (Fatma Ana'nın eli, Miryam'ın eli)", ["koruma", "bereket", "iyi talih"],
      "Avucunda göz bulunan açık el; kötülükten koruyan, bereket ve iyi talih getiren bir kalkan olarak görülür. Parmakları yukarı bakarken koruma, aşağı bakarken bolluk anlamı öne çıkar.",
      "Evin duvarına ya da kapısına asılır, takı olarak taşınır; çoğu zaman nazar boncuğuyla birlikte kullanılır."),
    S("horus-gozu", "Horus'un Gözü", "koruma", "Antik Mısır; gökyüzü tanrısı Horus'un iyileşen gözü", ["şifa", "koruma", "bütünlük"],
      "Efsanede yaralanıp iyileşen göz; bütünlüğün geri kazanılmasını, korunmayı ve sağlıklı görüşü temsil eder. Denizciler ve yolcular için koruma tılsımı olmuştur.",
      "Takılarda ve dövmelerde koruma ve iç görü niyetiyle kullanılır."),
    S("pentagram", "Pentagram", "koruma", "Antik Yunan'dan Orta Çağ Avrupa'sına; Pisagorcular sağlığın sembolü saydı", ["beş element", "koruma", "insan"],
      "Tek çizgiyle çizilen, ucu yukarı bakan beş köşeli yıldız; toprak, su, ateş, hava ve ruhun uyumunu, kolları ve bacakları açık insan bedenini anlatır. Daire içindeki hâli koruyucu kalkan olarak bilinir.",
      "Koruma ve denge niyetiyle takı ya da sunak sembolü olarak kullanılır."),
    S("muhur-suleyman", "Mühr-ü Süleyman", "koruma", "Ortadoğu, Osmanlı ve Avrupa geleneklerinde ortak; Hz. Süleyman'ın mührü olarak anılır", ["zıtların birliği", "koruma", "bilgelik"],
      "İç içe geçmiş iki üçgenden oluşan altı köşeli yıldız; yukarıyı (gök, ateş) ve aşağıyı (yer, su) birleştirir. Osmanlı mimarisinde, sikkelerde ve çinilerde koruyucu bir desen olarak sıkça görülür.",
      "Zıtların uyumunu ve bilgeliği temsil eden bir motif olarak; mimaride, el sanatlarında ve takılarda."),
    S("goz-ucgen", "Her Şeyi Gören Göz", "koruma", "Rönesans dönemi Avrupa sanatı; 'İlahi Takdirin Gözü'", ["ilahi gözetim", "farkındalık", "hakikat"],
      "Işık saçan üçgen içindeki göz; yaratılışın gözetildiğini ve hiçbir şeyin hakikatten gizlenemeyeceğini anlatır. Üçgen, üçlü birliği ve dengeyi simgeler.",
      "Farkındalık ve iç görü niyetiyle; sanat ve tasarımda."),
    S("hayat-cicegi", "Hayat Çiçeği", "geometri", "Antik Mısır tapınaklarından Rönesans defterlerine; birçok kültürde bulunur", ["yaratılış", "birlik", "uyum"],
      "Eşit aralıklı, iç içe geçmiş dairelerden oluşan altı yapraklı desen; yaratılışın kalıbı ve her şeyin birbirine bağlı olduğu fikri olarak görülür.",
      "Meditasyonda odak noktası, ev dekorasyonunda uyum sembolü olarak."),
    S("metatron", "Metatron Küpü", "geometri", "Kutsal geometri geleneği; Hayat Çiçeği'nden türetilir", ["denge", "yaratılışın yapısı", "koruma"],
      "On üç dairenin düz çizgilerle birleşmesinden doğan figür; içinde Platon katılarının tamamını barındırır. Evrenin yapı taşlarının bir haritası olarak yorumlanır.",
      "Enerji dengeleme ve odaklanma çalışmalarında."),
    S("sri-yantra", "Sri Yantra", "geometri", "Hint tantrik geleneği", ["bolluk", "yaratılış", "birlik"],
      "Dokuz iç içe geçmiş üçgen, lotus yaprakları ve kapılı bir kareyle çevrili; merkezdeki nokta (bindu) yaratılışın kaynağını, üçgenler eril ve dişil enerjilerin birleşimini temsil eder.",
      "Meditasyonda gözü merkeze odaklayarak; bolluk ve uyum niyetleriyle."),
    S("vesica", "Vesica Piscis", "geometri", "Antik geometri; Orta Çağ katedrallerinin mimarisinde", ["doğum", "birleşme", "geçit"],
      "Merkezleri birbirinin çevresinde olan iki dairenin kesiştiği badem şekli; iki dünyanın buluştuğu geçidi ve yeni olanın doğuşunu simgeler.",
      "Tasarımda, mimaride ve birlik temalı ritüellerde."),
    S("mandala", "Mandala", "geometri", "Hint ve Tibet gelenekleri; Sanskritçe 'çember'", ["bütünlük", "merkez", "meditasyon"],
      "Merkezden dışa açılan dairesel desen; evreni ve insanın iç dünyasını bir bütün olarak gösterir. Psikolog Carl Jung mandalayı benliğin sembolü olarak görmüştür.",
      "Mandala boyamak ya da çizmek zihni sakinleştiren bir meditasyon pratiği olarak."),
    S("labirent", "Labirent", "geometri", "Girit'ten Chartres Katedrali'ne; tek yollu yedi halkalı klasik labirent", ["iç yolculuk", "sabır", "merkeze varış"],
      "Tek bir yolun dolanarak merkeze ulaştığı desen; kaybolmak için değil, kendini bulmak için yürünen bir yolculuktur. Merkez, ruhun özüdür.",
      "Yürüme meditasyonunda ya da parmakla takip ederek zihni sakinleştirmek için."),
    S("ouroboros", "Ouroboros", "dongu", "Antik Mısır ve Yunan; simyacıların sembolü", ["sonsuzluk", "yeniden doğuş", "bütünlük"],
      "Kendi kuyruğunu ısıran yılan; her sonun bir başlangıç olduğunu, yaratılış ile yok oluşun sonsuz döngüsünü anlatır.",
      "Dönüşüm ve yenilenme dönemlerinde hatırlatıcı bir sembol olarak."),
    S("sonsuzluk", "Sonsuzluk (Lemniskat)", "dongu", "Matematikçi John Wallis'in 1655'te kullandığı işaret; daha eski düğüm motifleriyle akraba", ["sonsuzluk", "denge", "bağlılık"],
      "Yatık sekiz; başı ve sonu olmayan akışı, iki kutup arasındaki dengeyi ve bitmeyen bağlılığı simgeler.",
      "Aşk ve dostluk hediyelerinde, takılarda ve dövmelerde."),
    S("kelt-dugumu", "Kelt Düğümü", "dongu", "Kelt ve Ada sanatı (İrlanda, İskoçya); el yazmalarında ve taş haçlarda", ["sonsuz bağ", "hayatın akışı", "sadakat"],
      "Başı ve sonu olmayan iç içe geçmiş çizgiler; hayatın kesintisiz akışını ve kopmayan bağları anlatır.",
      "Sadakat ve dostluk sembolü olarak takılarda ve el sanatlarında."),
    S("triquetra", "Triquetra", "dongu", "Kelt sanatı; sonradan farklı geleneklerce de benimsendi", ["üçlü birlik", "koruma", "sonsuzluk"],
      "Üç iç içe geçmiş yaydan oluşan düğüm; beden, zihin ve ruhun ya da geçmiş, şimdi ve geleceğin birliğini simgeler.",
      "Koruma ve birlik niyetiyle takılarda."),
    S("triskel", "Triskel", "dongu", "Neolitik dönem Newgrange anıtı; Kelt kültürü", ["hareket", "ilerleme", "üç dünya"],
      "Merkezden dönen üç sarmal; hareketi, gelişimi ve yaşamın üç aşamasını (doğum, ölüm, yeniden doğuş) anlatır.",
      "İlerleme ve kişisel gelişim niyetiyle."),
    S("yin-yang", "Yin Yang", "dongu", "Antik Çin felsefesi, Taoculuk", ["denge", "zıtların uyumu", "dönüşüm"],
      "Siyah ve beyazın birbirine dönüştüğü daire; her zıtlığın içinde ötekinin tohumunu taşıdığını ve hayatın dengesini anlatır.",
      "Denge arayışında hatırlatıcı olarak; meditasyon ve dövüş sanatlarında."),
    S("dharma", "Dharma Çarkı", "bilgelik", "Hint kökenli Budist gelenek", ["doğru yol", "öğreti", "ilerleme"],
      "Sekiz kollu çark; erdemli yaşamın sekiz ilkesini ve öğretinin dünyada dönerek yayılmasını simgeler.",
      "Bilinçli yaşam ve doğru eylem niyetiyle."),
    S("om", "Om", "bilgelik", "Hint gelenekleri; kutsal ses", ["evrenin sesi", "birlik", "meditasyon"],
      "Evrenin ilk titreşimi kabul edilen kutsal hece; uyanıklık, rüya, derin uyku ve hepsinin ötesindeki bilinci temsil eder.",
      "Meditasyonun başında ve sonunda sesli tekrarlanır; yoga stüdyolarında yaygındır."),
    S("lotus", "Lotus Çiçeği", "bilgelik", "Antik Mısır ve Hint gelenekleri", ["arınma", "uyanış", "yeniden doğuş"],
      "Çamurun içinden lekesiz açan çiçek; zorlukların içinden saf ve aydınlanmış olarak yükselmeyi simgeler.",
      "Kişisel gelişim ve yeni başlangıç niyetiyle; meditasyon mekânlarında."),
    S("ankh", "Ankh", "bilgelik", "Antik Mısır hiyeroglifi", ["yaşam", "ölümsüzlük", "denge"],
      "Tepesi halkalı haç; 'yaşam' anlamına gelir. Tanrıların elinde, insanlara yaşam nefesi verirken resmedilir.",
      "Canlılık ve yaşam enerjisi niyetiyle takılarda."),
    S("caduceus", "Kadüse (Hermes Asası)", "bilgelik", "Antik Yunan; habercilerin ve Hermes'in asası", ["denge", "iletişim", "uzlaşma"],
      "İki yılanın sarıldığı kanatlı asa; zıt güçlerin dengesini, haberciliği ve uzlaşmayı simgeler. (Tıbbın sembolü tek yılanlı Asklepios asasıdır.)",
      "İletişim ve denge niyetiyle."),
    S("anahtar", "Anahtar", "bilgelik", "Birçok kültürde; gizli bilginin ve geçişin simgesi", ["sır", "fırsat", "geçiş"],
      "Kapıları açan anahtar; gizli bilgiye ulaşmayı, yeni fırsatları ve bir eşikten geçmeyi anlatır.",
      "Yeni başlangıçlarda ve sınav, iş gibi kapı açılması beklenen dönemlerde hatırlatıcı olarak."),
    S("hayat-agaci", "Hayat Ağacı", "doga", "Türk-Moğol (Kayın), İskandinav (Yggdrasil), Kabala ve daha birçok gelenek", ["bağlantı", "büyüme", "soy"],
      "Kökleri yerin altına, dalları göğe uzanan ağaç; yeraltı, yeryüzü ve gök dünyalarını birbirine bağlar. Eski Türk inancında gökle yeri bağlayan kutsal ağaçtır.",
      "Aile, köklerle bağ ve kişisel büyüme niyetiyle; halılarda ve süslemelerde."),
    S("kelebek", "Kelebek", "doga", "Evrensel; Antik Yunan'da 'psyche' hem ruh hem kelebek demektir", ["dönüşüm", "ruh", "hafiflik"],
      "Tırtıldan kozaya, kozadan kanada; derin bir dönüşümü ve ruhun özgürleşmesini anlatır.",
      "Değişim dönemlerinde cesaret veren bir sembol olarak."),
    S("yilan", "Yılan", "doga", "Birçok kültürde; kundalini enerjisi, şifa ve yenilenme", ["yenilenme", "bilgelik", "yaşam enerjisi"],
      "Derisini değiştirerek yenilenen yılan; dönüşümü, şifayı ve omurga boyunca yükselen yaşam enerjisini simgeler.",
      "Yenilenme ve iç güç niyetiyle."),
    S("kartal", "Kartal", "doga", "Orta Asya Türk geleneği, Anadolu Selçuklu çift başlı kartalı ve birçok kültür", ["güç", "vizyon", "özgürlük"],
      "Göğe en yükseğe uçan kuş; geniş bakış açısını, cesareti ve gökle yeryüzü arasındaki habercilikle ruhsal yükselişi simgeler.",
      "Liderlik, cesaret ve büyük resmi görme niyetiyle."),
    S("uclu-ay", "Üçlü Ay", "gok", "Eski Avrupa ve Akdeniz ay inançları", ["kadınsı döngü", "sezgi", "dönüşüm"],
      "Büyüyen hilal, dolunay ve küçülen hilal; başlangıç, olgunluk ve bilgeliği, kadının ve doğanın döngülerini anlatır.",
      "Ay ritüellerinde ve sezgiyi güçlendirme niyetiyle."),
    S("hilal", "Hilal ve Işık", "gok", "Ay'ı kutsal sayan birçok kadim kültür", ["yeni başlangıç", "umut", "sezgi"],
      "İçinde ışık küresi taşıyan hilal; karanlığın içinde doğan umudu, yeni başlangıcı ve sezginin rehberliğini simgeler.",
      "Yeni Ay niyetlerinde hatırlatıcı olarak."),
    S("gunes", "Güneş", "gok", "Evrensel; Hitit güneş kursundan Mısır'a, Orta Asya'dan Aztek'e", ["yaşam", "bilinç", "canlılık"],
      "Hayatın kaynağı, aydınlık ve bilinç; her sabah yeniden doğarak umudu ve yenilenmeyi anlatır.",
      "Canlılık, özgüven ve başarı niyetiyle."),
    S("spiral", "Spiral", "gok", "Tarih öncesi kaya resimlerinden galaksilere kadar evrensel", ["büyüme", "evrim", "yolculuk"],
      "Merkezden dışa açılan ya da içe dönen sarmal; doğadaki büyümeyi (deniz kabukları, galaksiler) ve ruhun gelişim yolculuğunu anlatır.",
      "Kişisel gelişim ve içe dönüş meditasyonlarında."),
  ];

  return { kategoriler, semboller, sembolBul: (id) => semboller.find((s) => s.id === id) };
});
